spring:
  mvc:
    static-path-pattern: /static/**
  jpa:
    hibernate:
      ddl-auto: none
  datasource:
    url: jdbc:mysql://192.168.10.51:3306/shop?serverTimezone=UTC
    username: root
    password: 0WN3PGgqsJ!%
management:
  endpoints:
    web:
      exposure:
        include: info, health, beans, mappings
